package jc;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
//package jclassdesign;

/**
 *
 * @author Steve
 */
public enum PropertyType {
    
    SELECTION_TOOL_ICON,
    SELECTION_TOOL_TOOLTIP,
    REMOVE_ICON,
    REMOVE_TOOLTIP,
    RECTANGLE_ICON,
    RECTANGLE_TOOLTIP,
    ELLIPSE_ICON,
    ELLIPSE_TOOLTIP,
    MOVE_TO_BACK_ICON,
    MOVE_TO_BACK_TOOLTIP,
    MOVE_TO_FRONT_ICON,
    MOVE_TO_FRONT_TOOLTIP,
    BACKGROUND_TOOLTIP,
    FILL_TOOLTIP,
    OUTLINE_TOOLTIP,
    SNAPSHOT_ICON,
    SNAPSHOT_TOOLTIP,

    ATTRIBUTE_UPDATE_ERROR_MESSAGE,
    ATTRIBUTE_UPDATE_ERROR_TITLE,
    ADD_ELEMENT_ERROR_MESSAGE,
    ADD_ELEMENT_ERROR_TITLE,
    REMOVE_ELEMENT_ERROR_MESSAGE,
    REMOVE_ELEMENT_ERROR_TITLE,
    ILLEGAL_NODE_REMOVAL_ERROR_MESSAGE, 
    ILLEGAL_NODE_REMOVAL_ERROR_TITLE,
    TEMP_PAGE_LOAD_ERROR_MESSAGE,
    TEMP_PAGE_LOAD_ERROR_TITLE,
    CSS_EXPORT_ERROR_MESSAGE,
    CSS_EXPORT_ERROR_TITLE,
    UPDATE_ERROR_MESSAGE,
    UPDATE_ERROR_TITLE,
    
    BACKGROUND_COLOR_LABEL,
    FILL_COLOR_LABEL,
    OUTLINE_COLOR_LABEL,
    OUTLINE_THICKNESS_LABEL
    
}
